# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting_scheduled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_quantum', models.IntegerField(choices=[(1, '8:00'), (2, '9:00'), (3, '10:00'), (4, '11:00'), (5, '12:00'), (6, '13:00'), (7, '14:00'), (8, '15:00'), (9, '16:00'), (10, '17:00')])),
            ],
        ),
        migrations.CreateModel(
            name='MettingRom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, null=True)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='meeting_scheduled',
            name='metting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metting.MettingRom'),
        ),
        migrations.AddField(
            model_name='meeting_scheduled',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metting.UserInfo'),
        ),
    ]
