# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metting', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meeting_scheduled',
            unique_together=set([('metting', 'date', 'time_quantum')]),
        ),
    ]
